index:
    path: /
    controller: App\Controller\DefaultController::index

tesseract_index:
    path: /ocr/
    controller:  App\Controller\TesseractController::index

tesseract_consult:
    path: /ocr/consult
    controller:  App\Controller\TesseractController::consult